### ISSUE TITLE
AndroidX compatability

### ISSUE THREAD

**Issue by justintuchek** [andrzejchm/RESTMock#100]
Hi 👋 

Would you be open to accepting a PR for enabling Android X support - or is it something that is already road mapped?

**Comment by andrzejchm** [comment]
Feel free! I'm always open to contributions and didn't have time myself to update it for androidx

**Comment by justintuchek** [comment]
Awesome! I'll get a PR up soon 👍 we're going through our migration now and are working towards getting off Jetifier

**Comment by abjerstedt** [comment]
@andrzejchm Any chance you could take a look at the #102?

**Comment by andrzejchm** [comment]
it got merged into master and will be a part of the next release
