### ISSUE TITLE
Question: What are your thoughts/plans on @Nullable @NotNullable annotations?

### ISSUE THREAD

**Issue by tir38** [andrzejchm/RESTMock#106]
I'm going to fix a potential NPE in the code base. I thought it would be helpful to annotate the potentially-null-variable as `@Nullable`. I see you don't do this anywhere yet. Do you have any plans to do this? Did you explicitly *not* do this?

**Comment by andrzejchm** [comment]
back when the library was developed there was no preferred way of annotating arguments with @Nullable nor @NotNull. I'm currently in the process of rewriting the library in Kotlin, so I believe that will fix the problem here

**Comment by tir38** [comment]
Ok if you are in the middle of a re-write I might not open a PR to fix the issue. 

Update: In fact when I went back to describe the issue I see that it was the same as #103. So I'm just going to grab the latest version.
