### ISSUE TITLE
got Problem with relative paths from android gradle plugin 3.5.0

### ISSUE THREAD

**Issue by jc-oma** [andrzejchm/RESTMock#107]
Hello,
I've got an issue using the gradle Plugin. With the last update I'm not able to open relative paths in my project. The issue appeared by upgrading `com.android.tools.build:gradle` from 3.4.2 to 3.5.0.
`thenReturnFile` is not able to open asset files and crashes when using mockserver in connected tests with the following error:
 ```
E/RESTMock: <- Response FILE READ ERROR
    java.io.FileNotFoundException
``` 

We could have brought it to work by using the following code: 
```
context.getAssets()
    .open(**FILEPATH**)
    .use { Log.d("test", it.bufferedReader().readLine()) }
```

**Comment by andrzejchm** [comment]
thanks for reporting this, I'll take a look

**Comment by andrzejchm** [comment]
I've tested this on 3.5.0 gradle plugin today and it works as intended:

* `thenReturnFile("api/response/GET_200_success.json")`
* file location: `${rootProject}/app/src/androidTest/assets/api/response/GET_200_success.json`

**Comment by jc-oma** [comment]
Hmm ok thank you very much for the fast answer. I really appreciate it. This is awkward.
