### ISSUE TITLE
Issue with Test not passing

### ISSUE THREAD

**Issue by mathemandy** [andrzejchm/RESTMock#108]
Hi Below is the error i keep getting when using Rest Mock Server in my project. 

I have followed the sample and still cant make it work. 
i don't have this issue when i copy my json or test to the android Sample.

Below are some screenshots of my project state to see if i can be assisted.

![Screenshot 2019-10-04 at 1 43 51 PM](https://user-images.githubusercontent.com/6526607/66208864-1014b000-e6ae-11e9-832e-0232272fb79e.png)

![Screenshot 2019-10-04 at 1 52 01 PM](https://user-images.githubusercontent.com/6526607/66209029-77cafb00-e6ae-11e9-89ae-b412b3d69d44.png)

![Screenshot 2019-10-04 at 1 52 18 PM](https://user-images.githubusercontent.com/6526607/66209049-7ef20900-e6ae-11e9-8ee8-91891cffd190.png)

I am using v0.4.0 of the Library to test this

**Comment by andrzejchm** [comment]
please make sure your app code is using the RESTMock's url as base url. according to the docs here: https://github.com/andrzejchm/RESTMock#step-6-specify-api-endpoint

I'll close the issue for now, If you still have problems, feel free to reopen it
