### ISSUE TITLE
Library not working for apps using current version of OkHttp (4.4.1)

### ISSUE THREAD

**Issue by shoeguy** [andrzejchm/RESTMock#110]
It appears that tests using RESTMock and failing for apps that use the current version of OkHttp.

The RESTMock library used 4.0.1 and the current version of OkHttp is 4.4.1

Here is the crash report from Flipper:

![image](https://user-images.githubusercontent.com/31056004/77695808-59b5c780-6f7a-11ea-9795-71af7867725b.png)

**Comment by andrzejchm** [comment]
I've published an update `0.4.2` that uses latest version of OkHttp

**Comment by shoeguy** [comment]
Thank-you so much.
