### ISSUE TITLE
Gradle error for version 0.1.2

### ISSUE THREAD

**Issue by MarcRubio** [andrzejchm/RESTMock#33]
Hi, when I try to include androidTestCompile 'com.github.andrzejchm.RESTMock:android:0.1.2', I get the following error:

Error:Module 'com.github.andrzejchm.RESTMock:android:0.1.2' depends on one or more Android Libraries but is a jar

But version 0.1.1 works fine with no issues. 

Thoughts?

**Comment by andrzejchm** [comment]
could You paste  `dependencies` part of your `build.gradle`?

**Comment by andrzejchm** [comment]
I think I found the issue. Could you please try with the `com.github.andrzejchm.RESTMock:android:0.1.3` version instead?

**Comment by MarcRubio** [comment]
Yea, that fixes it.
