### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by jwir3** [andrzejchm/RESTMock#43]
There have been a few features that have gone into the current development trunk. At my work, we're using jwir3/RESTMock instead of RESTMock's official distribution, because the features haven't been included yet. 

This is just a friendly reminder to prepare a distribution. @andrzejchm if you don't have time and would like some assistance, I'd be happy to help maintain the package for you if you give me access.

**Comment by andrzejchm** [comment]
Worry not, the release is already on the way! sorry for the delay. If you have any other feature requests, feel free to post them here and I will be more than happy to provide you with the solutions :)

**Comment by jwir3** [comment]
Thank you! 👍

**Comment by andrzejchm** [comment]
and... its done! version 0.1.4 hit the production! :)
