### ISSUE TITLE
Add delay to a response.

### ISSUE THREAD

**Issue by matoelorriaga** [andrzejchm/RESTMock#47]
Hi! would be really nice if we were able to do something like this:

```
whenGET(pathEndsWith("pokemon/1/"))
    .thenReturnFile(200, "getPokemonDetails_200.json")
    .delay(3, TimeUnit.SECONDS); // this!
```

Are there any plans to include something similar?

Thanks! Great work!

**Comment by andrzejchm** [comment]
implemented in `0.2.0` version, enjoy!

**Comment by matoelorriaga** [comment]
Great! When will 0.2.0 be available? Thanks!

**Comment by andrzejchm** [comment]
it's already released
