### ISSUE TITLE
Why not using OkHttp3?

### ISSUE THREAD

**Issue by Piasy** [andrzejchm/RESTMock#6]

**Comment by andrzejchm** [comment]
Thanks for the suggestion!

The time I was implementing this for the first time there was no OkHtt3 yet, but now there is no good reason to stay with v2, going to change that

**Comment by andrzejchm** [comment]
done

**Comment by Piasy** [comment]
@andrzejchm When will the new version be published?

**Comment by andrzejchm** [comment]
should be there by tomorrow morning

**Comment by andrzejchm** [comment]
and... its there v0.0.4
