### ISSUE TITLE
Gradle Dependency issue

### ISSUE THREAD

**Issue by pvrkchaitanya** [andrzejchm/RESTMock#60]
Hi,

I have added the dependency as 

dependencies {
	androidTestCompile 'com.github.andrzejchm.RESTMock:android:0.2.1'
}
also included the maven url in the project build.gradle.

But I am not able to access the api.

When I keep the below as dependency 

dependencies {
	compile 'com.github.andrzejchm.RESTMock:android:0.2.1'
}

then I am able to access the API.

Could you please let me know which one to follow

Thanks,
Chaitanya

**Comment by andrzejchm** [comment]
dependes on where you want to access it, unit tests? android tests? 
If you plan to use it with android tests (run on a device/emulator)
you have to add 

```groovy
androidTestCompile 'com.github.andrzejchm.RESTMock:android:0.2.1'
```
and have your tests classes located in `$projectRoot/app/src/androidTest/` folder.

On the other hand, if you plan to use it with jvm unit tests, then 

```groovy
testCompile 'com.github.andrzejchm.RESTMock:core:0.2.1'
```

and have your tests located in `$projectRoot/app/src/test/` folder.

**Comment by andrzejchm** [comment]
I assume the problem has been solved, closing
