### ISSUE TITLE
Delay not working

### ISSUE THREAD

**Issue by maximelebastard** [andrzejchm/RESTMock#62]
Hello, I've got a little issue with the delay method : 

**The code**

Here is the code, in a jUnit test:

```java
        RESTMockServer.whenRequested(pathContains(BernardAPI.LOGOUT))
                .thenReturnString(200, "test response")
                .delay(TimeUnit.SECONDS, 30);
        
        RESTMockServer.enableLogging(new RESTMockLogger() {
            @Override
            public void log(String message) {
                String m = message;
            }

            @Override
            public void error(String errorMessage) {
                String m = errorMessage;
            }

            @Override
            public void error(String errorMessage, Throwable exception) {
                String m = errorMessage;
            }
        });

        Boolean result = bernardWebService.logout();
```

I run it on debug mode and I have breakpoints in each of the RESTMockLogger methods.

**Expected behavior**

When I run bernardWebService.logout(), it triggers a HTTP Request on a logout URL, catched by RESTMockServer. As I defined a delay of 30 seconds, I expect the Mock webserver to wait 30 seconds before sending a response (and I hope to get a timeout to test this case).

**Actual behavior**

When bernardWebService.logout() is triggered, I get into RESTMockLogger.log with this message:

```
-> New Request:	GET /api/logout HTTP/1.1
```

About a second later, I'm back in my RESTMockLogger.log method with this message:

```
<- Response:	HTTP/1.1 200 OK
```

As you can see, no delay is applied.

I tried with days and milliseconds unit. I tried to call the delay method before and after calling thenReturnString, it still doesn't work.

**Comment by andrzejchm** [comment]
while the logs might be misleading, they are not an indicator of whether the functionality is working or not. By default, the http's response body gets delayed indeed, and logs are printed out as soon as the response dispatcher finds a match for given request.

To reiterate: Logs are immediately logging responses while the real response gets delivered after some delay. This is a good point though to delay logs aswell

**Comment by maximelebastard** [comment]
Ok, I get that !
But even when I do not watch the logs, the test ends in about 3 seconds - so I guess it is not working anyway.

What debug info can I give you ?

**Comment by andrzejchm** [comment]
is `bernardWebService.logout()` a synchronous call? if its not, that is the case why tests finish before actual response gets delivered.

**Comment by maximelebastard** [comment]
bernardWebService.logout() calls a Retrofit API method:

```java
public boolean logout() throws IOException {
        // BernardAPI is an interface using Retrofit annotations
        Response<Void> response = BernardAPI.logout().execute();
        return response.code() == 200;
    }
```

The execute method of retrofit is synchronous, as written on its javadoc:
```java
  /**
   * Synchronously send the request and return its response.
   *
   * @throws IOException if a problem occurred talking to the server.
   * @throws RuntimeException (and subclasses) if an unexpected error occurs creating the request
   * or decoding the response.
   */
  Response<T> execute() throws IOException;
```

**Comment by andrzejchm** [comment]
Keep in mind MockWebServer, followed by RESTMock, delays the body of a response, not the entire response. so what you'd have to do is to wait for the entire body to arrive and then check the response.code. So something like this:

```java
public boolean logout() throws IOException {
        // BernardAPI is an interface using Retrofit annotations
        Response<Void> response = BernardAPI.logout().execute();
        String body = response.body().string()
        return response.code() == 200 && body != null && !body.isEmpty();
    }
```
take a look into https://github.com/andrzejchm/RESTMock/commit/f7df1a402b0f56b06a6a404cf7684777b4502b92 for a unit test that demonstrates this behavior
