### ISSUE TITLE
Intercept request for dynamic responses?

### ISSUE THREAD

**Issue by Simon-Kaz** [andrzejchm/RESTMock#71]
Is it possible to intercept the request ? I'd like to adjust the response based on the parameters sent in the request (both in body and the url)

For example - When I send a request to the server with a specific ID (json body), I need the response from the server to contain the same ID. 

With wiremock I used https://github.com/opentable/wiremock-body-transformer

**Comment by andrzejchm** [comment]
this is definetely a good idea and will be a part of the upcoming release

**Comment by andrzejchm** [comment]
solved in #74
