### ISSUE TITLE
"There are more than one response matching" for identical request/response combination?

### ISSUE THREAD

**Issue by oradkovsky** [andrzejchm/RESTMock#75]
Hi Andrew,

Thanks for great library! 

I am facing either a bug or misuse situation, here is the scenario:

1. Let's say we have instrumentation test that does mocking like this:
`RESTMockServer.whenGET(pathContains(".../" + valueLongId))
.thenReturnString(responseJson)`
2. The above runs just fine as a separate test
3. Let's copy-paste the test, keeping the above mocking identical. Once our suite of 2 tests runs, one of the tests will fail with "java.lang.IllegalStateException: There are more than one response matching this request..."

For the above scenario, I would expect mocking to work because from test perspective both specified requests and responses are identical? Lib version 0.2.1.

**Comment by andrzejchm** [comment]
@oradkovsky thanks for posting the question. Baically, RESTMock does not track duplications of mocks, thus if you don't "clean" after each test, you run into duplcated mock situation which is reported as "more than one response matching" scenario. What you can do is either:
* run `RESTMockServer.reset()` before each test run and before specifying mocks in `@Before`-annotated method, or:
* run the same statement in your `@After`-annotated method :)

Hope it helps!

**Comment by oradkovsky** [comment]
Tested. It certainly works! Originally I did try reset() but in a wrong way, so it's misuse on my end. Thanks!
