### ISSUE TITLE
MockAnswer is not public

### ISSUE THREAD

**Issue by SmasSive** [andrzejchm/RESTMock#79]
Hi,

First of all thank you for this awesome library!

We are trying to intercept the request to check POST's body parameters to return a response depending on a body parameter value. We are trying to do that with the method `thenAnswer` that needs as a parameter a `io.appflate.restmock.MockAnswer` but this interface is not public so we cannot access to it.

This is intentional? If it is, how can we achieve our goal to return a response depending on a body parameter?
If it's not, please could you make it public?

Thanks!

**Comment by andrzejchm** [comment]
You're definetely right about it should be public. It worked though without being public since lambdas don't need the interface to be public to work. Fixed in 0.3.1 release
