### ISSUE TITLE
Expose underlying MockWebServer or support assertions

### ISSUE THREAD

**Issue by tir38** [andrzejchm/RESTMock#87]
MockWebServer allows us to assert that certain web requests were made:

```
 // Optional: confirm that your app made the HTTP requests you were expecting.
  RecordedRequest request1 = server.takeRequest();
  assertEquals("/v1/chat/messages/", request1.getPath());
  assertNotNull(request1.getHeader("Authorization"));

  RecordedRequest request2 = server.takeRequest();
  assertEquals("/v1/chat/messages/2", request2.getPath());

  RecordedRequest request3 = server.takeRequest();
  assertEquals("/v1/chat/messages/3", request3.getPath());
```

This functionality isn't wrapped by RESTMock. It would be great if we could used this half of MockWebServer.

At the very least, RESTMock should expose the mock server so we can manually assert; TL;DR `RESTMockServer.mockWebServer` should be public or exposed by getter

**Comment by andrzejchm** [comment]
https://github.com/andrzejchm/RESTMock#request-verification

**Comment by tir38** [comment]
Ahh thanks. Sorry about that. I searched for the wrong keyword https://github.com/andrzejchm/RESTMock/search?q=assert&type=Code
