### ISSUE TITLE
Method thenReturnFile() catch FileNotFoundException when file path contains blank space

### ISSUE THREAD

**Issue by oubowu** [andrzejchm/RESTMock#89]
When I write code like "RESTMockServer.whenGET(RequestMatchers.pathContains("users")).thenReturnFile(200, "json/users.json)",
  the json file path is "E:\Android Projects\Leetcode\app\build\intermediates\sourceFolderJavaResources\test\debug\json\users.json", the test result is "java.io.FileNotFoundException: E:\Android%20Projects\Leetcode\app\build\intermediates\sourceFolderJavaResources\test\debug\json\users.json ". Is that any bug with the source code?

**Comment by andrzejchm** [comment]
where is your `users.json` being placed? In order for it to work properly with default settings, it should be placed in `src/androidTest/assets/json/users.json`. That is, if you use `new AndroidAssetsFileParser(getContext())` while starting your RESTMockServer instance
