### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.appflate.restmock.MatchableCallsRequestDispatcher.removeAllMatchableCalls()

### ISSUE THREAD

**Issue by tir38** [andrzejchm/RESTMock#90]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.appflate.restmock.MatchableCallsRequestDispatcher.removeAllMatchableCalls()' on a null object reference
    at io.appflate.restmock.RESTMockServer.reset(RESTMockServer.java:130)
    at com.example.e2etests.tests.AbstractTest.tearDown(AbstractTest.java:61)
```

We just started getting this crash on some our tests.  It's happening in our test `@After` tear down method. Looking at the RESTMock source I guess this is possible if RestMock is not initialized. But we are initializing RESTMock when our test application starts

```
      AndroidAssetsFileParser restMockFileParser = new AndroidAssetsFileParser(InstrumentationRegistry.getContext());
        RESTMockServerStarter.startSync(restMockFileParser, new AndroidLogger());
```

And of course this was working just fine until this week. We are on version 0.3.2

**Comment by andrzejchm** [comment]
As you've mentioned, the situation where such null pointer is thrown is when the RESTMockServer is not initialized and you attempt some actions upon it (like calling any static method on `RESTMockServer` class. Is it possible that the `@After` teardown method is being called before the initialization of restmock? It highly depends on where is the `startSync` method being called and if you use unit or android tests.

**Comment by tir38** [comment]
i think it's happening because the app is still "going" after our test completes. So even though we correctly reset Restmock in @After the app is still chugging along and eventually makes another web request after test completes.
